image:
    - macOS
    - Ubuntu
    - Visual Studio 2019

platform:
    - x64

environment:
    APPVEYOR_YML_DISABLE_PS_LINUX: true

for:
    - matrix:
          only:
              - image: macOS
      environment:
          CC_CLANG: /usr/local/opt/llvm/bin/clang
          CXX_CLANG: /usr/local/opt/llvm/bin/clang++
          CXXFLAGS_CLANG: -stdlib=libc++
          CC_GCC: gcc-9
          CXX_GCC: g++-9
      install:
          - brew install ninja llvm gcc

    - matrix:
          only:
              - image: Ubuntu
      environment:
          CC_CLANG: clang-9
          CXX_CLANG: clang++-9
          CXXFLAGS_CLANG: -stdlib=libc++
          CC_GCC: gcc-9
          CXX_GCC: g++-9
      install:
          - curl -s https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          - sudo apt-add-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          - sudo apt-get update
          - sudo apt-get -y --allow-change-held-packages remove clang-9 mssql-server
          - sudo apt-get -y autoremove
          - sudo apt-get -y install clang-9 libc++-9-dev libc++abi-9-dev

    - matrix:
          only:
              - image: Visual Studio 2019

before_build:
    # ---- Mac & Linux ----
    # install Vcpkg
    - sh: /bin/bash .ci/install-vcpkg.sh

    # ---- Windows ----
    # install Vcpkg
    - ps: .ci\install-vcpkg.ps1

build_script:
    # ---- Mac & Linux ----
    # build project with Clang
    - sh: CC=$CC_CLANG CXX=$CXX_CLANG CXXFLAGS=$CXXFLAGS_CLANG /bin/bash .ci/build-project.sh build-clang
    - sh: ./build-clang/show_info
    - sh: ./build-clang/example
    - sh: ./build-clang/example_tests
    # build project with GCC
    - sh: CC=$CC_GCC CXX=$CXX_GCC /bin/bash .ci/build-project.sh build-gcc
    - sh: ./build-gcc/show_info
    - sh: ./build-gcc/example
    - sh: ./build-gcc/example_tests

    # ---- Windows ----
    # build project with MSVC
    - ps: .ci\build-project.ps1 build-msvc
    - ps: .\build-msvc\src\show_info\RelWithDebInfo\show_info.exe
    - ps: .\build-msvc\src\example\RelWithDebInfo\example.exe
    - ps: .\build-msvc\src\example\RelWithDebInfo\example_tests.exe
