image:
  - Visual Studio 2019

platform:
  - x64

install:
  - ps: Get-ChildItem "Env:" | Sort Name
  - ps: dir
  - ps: cd $Env:HOMEPATH
  - ps: dir
  - ps: New-Alias -Name git -Value "$Env:ProgramFiles\Git\bin\git.exe"
  - ps: $Env:GIT_REDIRECT_STDERR = '2>&1'
  - ps: git clone --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-msvc
  - ps: cd vcpkg-msvc
  - ps: .\bootstrap-vcpkg.bat -disableMetrics
  - ps: .\vcpkg install benchmark pcre pcre2
  - ps: cd "$Env:APPVEYOR_BUILD_FOLDER"

build_script:
  - ps: mkdir build-msvc && cd build-msvc
  - ps: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$Env:HOMEPATH\vcpkg-msvc\scripts\buildsystems\vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - ps: dir
  - ps: cat compile_commands.json
  - ps: cmake --build . --config Release -j 2
