image:
  - Visual Studio 2019

platform:
  - x64

install:
  - ps: cd $Env:HOMEPATH
  - ps: $Env:GIT_REDIRECT_STDERR = '2>&1'
  - ps: New-Alias -Name git -Value "$Env:ProgramFiles\Git\bin\git.exe"
  - ps: git clone --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-msvc
  - ps: cd vcpkg-msvc
  - ps: .\bootstrap-vcpkg.bat -disableMetrics
  - ps: $packages = Get-Content .vcpkg
  - ps: .\vcpkg install --triplet x64-windows $packages
  - ps: cd $Env:APPVEYOR_BUILD_FOLDER

build_script:
  - ps: dir $Env:HOMEPATH\vcpkg-msvc\scripts\buildsystems\vcpkg.cmake
  - ps: mkdir build-msvc
  - ps: cd build-msvc
  - ps: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE="$Env:HOMEPATH\vcpkg-msvc\scripts\buildsystems\vcpkg.cmake" ..
  - ps: cmake --build .
