image:
  - macOS
  - Ubuntu
  - Visual Studio 2019

platform:
  - x64

for:
-
  matrix:
    only:
      - image: macOS

  install:
    - brew install ninja llvm gcc
    - pushd $HOME
    - git clone --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-clang
    - cd vcpkg-clang
    - CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ ./bootstrap-vcpkg.sh --disableMetrics
    - CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
    - cd ..
    - git clone --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-gcc
    - cd vcpkg-gcc
    - CC=gcc-9 CXX=g++-9 ./bootstrap-vcpkg.sh --disableMetrics
    - CC=gcc-9 CXX=g++-9 ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
    - popd

  build_script:
    - mkdir build-clang && cd build-clang
    - CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg-clang/scripts/buildsystems/vcpkg.cmake ..
    - cmake --build .
    - cd ..
    - mkdir build-gcc && cd build-gcc
    - CC=gcc-9 CXX=g++-9 cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg-gcc/scripts/buildsystems/vcpkg.cmake ..
    - cmake --build .

-
  matrix:
    only:
      - image: Ubuntu

  install:
    - sudo apt-get install ninja-build
    - pushd $HOME
    - rm -rf vcpkg
    - git clone --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-clang
    - cd vcpkg-clang
    - CC=clang-9 CXX=clang++-9 ./bootstrap-vcpkg.sh --disableMetrics
    - CC=clang-9 CXX=clang++-9 ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
    - cd ..
    - git clone --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-gcc
    - cd vcpkg-gcc
    - CC=gcc-9 CXX=g++-9 ./bootstrap-vcpkg.sh --disableMetrics
    - CC=gcc-9 CXX=g++-9 ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
    - popd

  build_script:
    - mkdir build-clang && cd build-clang
    - CC=clang-9 CXX=clang++-9 cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg-clang/scripts/buildsystems/vcpkg.cmake ..
    - cmake --build .
    - cd ..
    - mkdir build-gcc && cd build-gcc
    - CC=gcc-9 CXX=g++-9 cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg-gcc/scripts/buildsystems/vcpkg.cmake ..
    - cmake --build .

-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - ps: cd $HOME
    - ps: git clone --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-msvc
    - ps: cd vcpkg-msvc
    - ps: ./bootstrap-vcpkg.bat --disableMetrics
    - ps: ./vcpkg install benchmark pcre pcre2
    - ps: cd $APPVEYOR_BUILD_FOLDER

  build_script:
    - ps: mkdir build-msvc && cd build-msvc
    - ps: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg-msvc/scripts/buildsystems/vcpkg.cmake ..
    - ps: cmake --build .
