image:
  - macOS
  - Ubuntu

platform:
  - x64

for:
-
  matrix:
    only:
      - image: macOS

  install:
    - brew install llvm
    - pushd -q $HOME
    - git clone --depth 1 https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ ./bootstrap-vcpkg.sh --disableMetrics
    - CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
    - popd -q

  build_script:
    - mkdir build-clang && cd build-clang
    - CC=/usr/local/opt/llvm/bin/clang CXX=/usr/local/opt/llvm/bin/clang++ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
    - cmake --build . -j 2
    - cd ..
    - mkdir build-gcc && cd build-gcc
    - CC=gcc-9 CXX=g++-9 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
    - cmake --build . -j 2

-
  matrix:
    only:
      - image: Ubuntu

  install:
    - pushd -q $HOME
    - rm -rf vcpkg
    - git clone --depth 1 https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - CC=gcc-9 CXX=g++-9 ./bootstrap-vcpkg.sh --disableMetrics
    - CC=gcc-9 CXX=g++-9 ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
    - popd -q

  build_script:
    - mkdir build-clang && cd build-clang
    - CC=clang-9 CXX=clang++-9 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
    - cmake --build . -j 2
    - cd ..
    - mkdir build-gcc && cd build-gcc
    - CC=gcc-9 CXX=g++-9 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
    - cmake --build . -j 2
