image:
  - macOS
  - Ubuntu

platform:
  - x64

for:
-
  matrix:
    only:
      - image: macOS

  install:
    - brew install llvm
    - pushd $HOME
    - git clone --depth 1 https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh --disableMetrics --allowAppleClang
    - ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
    - popd

  build_script:
    - mkdir build-clang && cd build-clang
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ ..
    - cmake --build . -j 2
    - cd ..
    - mkdir build-gcc && cd build-gcc
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 ..
    - cmake --build . -j 2

-
  matrix:
    only:
      - image: Ubuntu

  install:
    - pushd $HOME
    - rm -rf vcpkg
    - git clone --depth 1 https://github.com/Microsoft/vcpkg.git
    - cd vcpkg
    - ./bootstrap-vcpkg.sh --disableMetrics
    - ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
    - popd

  build_script:
    - mkdir build-clang && cd build-clang
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=clang-9 -DCMAKE_CXX_COMPILER=clang++-9 ..
    - cmake --build . -j 2
    - cd ..
    - mkdir build-gcc && cd build-gcc
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 ..
    - cmake --build . -j 2
