image:
  - macOS
  - Ubuntu
  - Visual Studio 2019

platform:
  - x64

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true


for:
-
  matrix:
    only:
      - image: macOS
  environment:
    CC_CLANG: /usr/local/opt/llvm/bin/clang
    CXX_CLANG: /usr/local/opt/llvm/bin/clang++
    CC_GCC: gcc-9
    CXX_GCC: g++-9
  install:
    - brew install ninja llvm gcc

-
  matrix:
    only:
      - image: Ubuntu
  environment:
    CC_CLANG: clang-9
    CXX_CLANG: clang++-9
    CC_GCC: gcc-9
    CXX_GCC: g++-9
  install:
    - sudo apt-get install ninja-build

-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
    - ps: New-Alias -Name git -Value "$Env:ProgramFiles\Git\bin\git.exe"


before_build:
  - sh: pushd $HOME
  - sh: git clone --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-clang
  - sh: cd vcpkg-clang
  - sh: CC=$CC_CLANG CXX=$CXX_CLANG ./bootstrap-vcpkg.sh --disableMetrics
  - sh: CC=$CC_CLANG CXX=$CXX_CLANG ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
  - sh: cd ..
  - sh: git clone --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-gcc
  - sh: cd vcpkg-gcc
  - sh: CC=$CC_GCC CXX=$CXX_GCC ./bootstrap-vcpkg.sh --disableMetrics
  - sh: CC=$CC_GCC CXX=$CXX_GCC ./vcpkg install $(< $APPVEYOR_BUILD_FOLDER/.vcpkg)
  - sh: popd

  # checkout and build Vcpkg in $HOME
  - ps: cd $Env:HOMEPATH
  - ps: git clone --quiet --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg-msvc
  - ps: cd vcpkg-msvc
  - ps: .\bootstrap-vcpkg.bat -disableMetrics
  # install packages listed in .vcpkg
  - ps: $packages = Get-Content "$Env:APPVEYOR_BUILD_FOLDER\.vcpkg"
  - ps: .\vcpkg install --triplet x64-windows $packages
  - ps: cd $Env:APPVEYOR_BUILD_FOLDER


build_script:
  - sh: mkdir build-clang && cd build-clang
  - sh: CC=$CC_CLANG CXX=$CXX_CLANG cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg-clang/scripts/buildsystems/vcpkg.cmake ..
  - sh: cmake --build .
  - sh: cd ..
  - sh: mkdir build-gcc && cd build-gcc
  - sh: CC=$CC_GCC CXX=$CXX_GCC cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg-gcc/scripts/buildsystems/vcpkg.cmake ..
  - sh: cmake --build .

  - ps: mkdir build-msvc
  - ps: cd build-msvc
  - ps: cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE="$Env:HOMEPATH\vcpkg-msvc\scripts\buildsystems\vcpkg.cmake" ..
  - ps: cmake --build .
