image:
  - macOS
  - Ubuntu
  - Visual Studio 2019

platform:
  - x64

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

for:
-
  matrix:
    only:
      - image: macOS
  environment:
    CC_CLANG: /usr/local/opt/llvm/bin/clang
    CXX_CLANG: /usr/local/opt/llvm/bin/clang++
    CXXFLAGS_CLANG: -stdlib=libc++
    CC_GCC: gcc-9
    CXX_GCC: g++-9
  install:
    - brew install ninja llvm gcc

-
  matrix:
    only:
      - image: Ubuntu
  environment:
    CC_CLANG: clang-9
    CXX_CLANG: clang++-9
    CXXFLAGS_CLANG: -stdlib=libc++
    CC_GCC: gcc-9
    CXX_GCC: g++-9
  install:
    - curl -s https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-add-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
    - sudo apt-get update
    - sudo apt-get -y --allow-change-held-packages remove clang-9 mssql-server
    - sudo apt-get -y autoremove
    - sudo apt-get -y install clang-9 libc++-9-dev libc++abi-9-dev

-
  matrix:
    only:
      - image: Visual Studio 2019
  install:
    - ps: New-Alias -Name git -Value "$Env:ProgramFiles\Git\bin\git.exe"


before_build:
  # ---- Mac & Linux ----
  # build Vcpkg and install packages (from .vcpkg) with Clang
  - sh: CC=$CC_CLANG CXX=$CXX_CLANG CXXFLAGS=$CXXFLAGS_CLANG sh .ci/install-vcpkg.sh $APPVEYOR_BUILD_FOLDER vcpkg-clang
  # build Vcpkg and install packages (from .vcpkg) with GCC
  - sh: CC=$CC_GCC CXX=$CXX_GCC sh .ci/install-vcpkg.sh $APPVEYOR_BUILD_FOLDER vcpkg-gcc

  # ---- Windows ----
  # build Vcpkg and install packages (from .vcpkg) with MSVC
  - ps: .ci\install-vcpkg.ps1 "$Env:APPVEYOR_BUILD_FOLDER"


build_script:
  # ---- Mac & Linux ----
  # build project with Clang
  - sh: CC=$CC_CLANG CXX=$CXX_CLANG CXXFLAGS=$CXXFLAGS_CLANG sh .ci/build-project.sh $HOME/vcpkg-clang build-clang
  - sh: ./build-clang/example_simple
  # build project with GCC
  - sh: CC=$CC_GCC CXX=$CXX_GCC sh .ci/build-project.sh $HOME/vcpkg-gcc build-gcc
  - sh: ./build-gcc/example_simple

  # ---- Windows ----
  # build project with MSVC
  - ps: mkdir build-msvc
  - ps: cd build-msvc
  - ps: cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE="$Env:HOMEPATH\vcpkg-msvc\scripts\buildsystems\vcpkg.cmake" ..
  - ps: cmake --build . --config Release
  - ps: .\Release\example_simple.exe
