language: cpp

jobs:
  include:
    # Use Clang 9 (installed via Homebrew) to run the tests and GCC 9 (default installed by Homebrew) to compile Vcpkg.
    # GCC 9 needs xcode10.3 to be able to run.
    # Clang 9 installation needs "update: true" to prevent "Error: Unknown command: bundle" Homebrew message.
    - os: osx
      osx_image: xcode10.3
      name: "osx: clang-9"
      addons:
        homebrew:
          packages:
            - llvm
          update: true
      env:
        - CC=/usr/local/opt/llvm/bin/clang
        - CXX=/usr/local/opt/llvm/bin/clang++
        - VCPKG_CC=gcc-9
        - VCPKG_CXX=g++-9

    # Use GCC 9 (default installed by Homebrew) to compile Vcpkg and run the tests.
    # GCC 9 needs xcode10.3 to be able to run.
    - os: osx
      osx_image: xcode10.3
      name: "osx: gcc-9"
      env:
        - CC=gcc-9
        - CXX=g++-9
        - VCPKG_CC=$CC
        - VCPKG_CXX=$CXX

    - os: linux
      dist: bionic
      name: "linux: clang-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          packages:
            - clang-9
      env:
        - CC=clang-9
        - CXX=clang++-9
        - VCPKG_CC=$CC
        - VCPKG_CXX=$CXX

    - os: linux
      dist: bionic
      name: "linux: gcc-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9
        - VCPKG_CC=$CC
        - VCPKG_CXX=$CXX

install:
  - PROJECT_DIR=`pwd`
  - pushd $HOME
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - CC=$VCPKG_CC CXX=$VCPKG_CXX ./bootstrap-vcpkg.sh --disableMetrics
  - ./vcpkg install $(< $PROJECT_DIR/.vcpkg)
  - popd

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . -j 2
