language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      name: "osx: clang"
      env:
        - COMPILER_DEFS=""

    - os: osx
      osx_image: xcode11.3
      name: "osx: gcc-8"
      env:
        - COMPILER_DEFS="brew install gcc@8 && CC=gcc-8 && CXX=g++-8"

    - os: osx
      osx_image: xcode11.3
      name: "osx: gcc-7"
      env:
        - COMPILER_DEFS="brew install gcc@7 && CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode11.3
      name: "osx: gcc-6"
      env:
        - COMPILER_DEFS="brew install gcc@6 && CC=gcc-6 && CXX=g++-6"

    - os: osx
      osx_image: xcode11.3
      name: "osx: gcc-8"
      env:
        - COMPILER_DEFS="brew install gcc@8 && CC=gcc-8 && CXX=g++-8"

    - os: osx
      osx_image: xcode11.3
      name: "osx: gcc-9"
      env:
        - COMPILER_DEFS="brew install gcc@9 && CC=gcc-9 && CXX=g++-9"

    - os: osx
      osx_image: xcode10.3
      env:
        - COMPILER_DEFS="brew install gcc@8 && CC=gcc-8 && CXX=g++-8"

    - os: linux
      dist: bionic
      name: "linux: clang-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          packages:
            - clang-9
      env:
         - COMPILER_DEFS="CC=clang-9 && CXX=clang++-9"

    - os: linux
      dist: bionic
      name: "linux: gcc-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-9
      env:
         - COMPILER_DEFS="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${COMPILER_DEFS}"

install:
  - pushd $HOME
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh --disableMetrics
  - ./vcpkg integrate install
  - ./vcpkg install pcre pcre2 benchmark
  - popd

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . -j 2
