language: cpp

jobs:
  include:
    # Build project with: Clang 9 (installed via Homebrew). Needs "update: true" to prevent "Error: Unknown command: bundle" Homebrew message.
    # Build Vcpkg with: GCC 9 (default installed by Homebrew). Needs xcode10.3 to be able to run.
    # Need to build Vcpkg with GCC on macOS 10.14 or older because the filesystem library is only available since macOS 10.15.
    - os: osx
      osx_image: xcode10.3
      name: "osx: clang-9"
      addons:
        homebrew:
          packages:
            - ninja
            - llvm
          update: true
      env:
        - CC=/usr/local/opt/llvm/bin/clang
        - CXX=/usr/local/opt/llvm/bin/clang++
        - CXXFLAGS=-stdlib=libc++
        - VCPKG_CC=gcc-9
        - VCPKG_CXX=g++-9
        - VCPKG_CXXFLAGS=

    # Build project with: GCC 9 (default installed by Homebrew). Needs xcode10.3 to be able to run.
    # Build Vcpkg with: GCC 9 (default installed by Homebrew). Needs xcode10.3 to be able to run.
    - os: osx
      osx_image: xcode10.3
      name: "osx: gcc-9"
      addons:
        homebrew:
          packages:
            - ninja
          update: true
      env:
        - CC=gcc-9
        - CXX=g++-9
        - CXXFLAGS=
        - VCPKG_CC=$CC
        - VCPKG_CXX=$CXX
        - VCPKG_CXXFLAGS=$CXXFLAGS

    # Build project with: Clang 9.
    # Build Vcpkg with: Clang 9.
    - os: linux
      dist: bionic
      name: "linux: clang-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          packages:
            - ninja-build
            - clang-9
      env:
        - CC=clang-9
        - CXX=clang++-9
        - CXXFLAGS=-stdlib=libc++
        - VCPKG_CC=$CC
        - VCPKG_CXX=$CXX
        - VCPKG_CXXFLAGS=$CXXFLAGS

    # Build project with: GCC 9.
    # Build Vcpkg with: GCC 9.
    - os: linux
      dist: bionic
      name: "linux: gcc-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - ninja-build
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9
        - CXXFLAGS=
        - VCPKG_CC=$CC
        - VCPKG_CXX=$CXX
        - VCPKG_CXXFLAGS=$CXXFLAGS

install:
  - pushd $HOME
  - git clone --depth 1 https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  # build Vcpkg itself with $VCPKG_CC and $VCPKG_CXX
  - CC=$VCPKG_CC CXX=$VCPKG_CXX CXXFLAGS=$VCPKG_CXXFLAGS ./bootstrap-vcpkg.sh --disableMetrics
  # build Vcpkg packages with $CC/$CXX
  - ./vcpkg install $(< $TRAVIS_BUILD_DIR/.vcpkg)
  - popd

script:
  # build project with $CC/$CXX
  - mkdir build && cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build .
  - ./example_simple
