language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      name: "osx: clang"
      env:
        - COMPILERS=""

    - os: osx
      osx_image: xcode11.3
      name: "osx: gcc-8"
      env:
        - COMPILERS="brew install gcc@8 && CC=gcc-8 && CXX=g++-8"

    - os: linux
      dist: bionic
      name: "linux: clang-9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          packages:
            - clang-9
      env:
         - COMPILERS="CC=clang-9 && CXX=clang++-9"

    - os: linux
      dist: bionic
      name: "linux: gcc-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - gcc-9
      env:
         - COMPILERS="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${COMPILERS}"

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . -j 2
