language: cpp

jobs:
  include:
    # Build project with: Clang 9 (installed via Homebrew). Needs "update: true" to prevent "Error: Unknown command: bundle" Homebrew message.
    # Build Vcpkg with: GCC 9 (default installed by Homebrew). Needs xcode10.3 to be able to run.
    # Need to build Vcpkg with GCC on macOS 10.14 or older because the filesystem library is only available since macOS 10.15.
    - os: osx
      osx_image: xcode10.3
      name: "osx: clang-9"
      addons:
        homebrew:
          packages:
            - ninja
            - llvm
          update: true
      env:
        - CC=/usr/local/opt/llvm/bin/clang
        - CXX=/usr/local/opt/llvm/bin/clang++
        - CXXFLAGS=-stdlib=libc++
        - VCPKG_CC=gcc-9
        - VCPKG_CXX=g++-9
        - VCPKG_CXXFLAGS=

    # Build project with: GCC 9 (default installed by Homebrew). Needs xcode10.3 to be able to run.
    # Build Vcpkg with: GCC 9 (default installed by Homebrew). Needs xcode10.3 to be able to run.
    - os: osx
      osx_image: xcode10.3
      name: "osx: gcc-9"
      addons:
        homebrew:
          packages:
            - ninja
          update: true
      env:
        - CC=gcc-9
        - CXX=g++-9
        - CXXFLAGS=
        - VCPKG_CC=$CC
        - VCPKG_CXX=$CXX
        - VCPKG_CXXFLAGS=$CXXFLAGS

    # Build project with: Clang 9.
    # Build Vcpkg with: Clang 9.
    - os: linux
      dist: bionic
      name: "linux: clang-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          packages:
            - ninja-build
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
      env:
        - CC=clang-9
        - CXX=clang++-9
        - CXXFLAGS=-stdlib=libc++
        - VCPKG_CC=$CC
        - VCPKG_CXX=$CXX
        - VCPKG_CXXFLAGS=$CXXFLAGS

    # Build project with: GCC 9.
    # Build Vcpkg with: GCC 9.
    - os: linux
      dist: bionic
      name: "linux: gcc-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - ninja-build
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9
        - CXXFLAGS=
        - VCPKG_CC=$CC
        - VCPKG_CXX=$CXX
        - VCPKG_CXXFLAGS=$CXXFLAGS

install:
  # build Vcpkg itself with $VCPKG_{CC,CXX,CXXFLAGS} and the Vcpkg packages with $CC/$CXX/$CXXFLAGS
  - /bin/bash .ci/install-vcpkg.sh "$TRAVIS_BUILD_DIR"

script:
  # build project with $CC/$CXX
  - /bin/bash .ci/build-project.sh
  - ./build/example_simple
