language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode10.3
      compiler: clang
      name: "osx: clang-9"
      addons:
        homebrew:
          packages:
            - llvm
      env:
        - CC=clang-9
        - CXX=clang++-9
        - VCPKG_CC=gcc-9
        - VCPKG_CXX=g++-9

    - os: osx
      osx_image: xcode10.3
      name: "osx: gcc-9"
      env:
        - CC=gcc-9
        - CXX=g++-9
        - VCPKG_CC=gcc-9
        - VCPKG_CXX=g++-9

    - os: linux
      dist: bionic
      name: "linux: clang-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          packages:
            - clang-9
      env:
        - CC=clang-9
        - CXX=clang++-9
        - VCPKG_CC=clang-9
        - VCPKG_CXX=clang++-9

    - os: linux
      dist: bionic
      name: "linux: gcc-9"
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - g++-9
      env:
        - CC=gcc-9
        - CXX=g++-9
        - VCPKG_CC=gcc-9
        - VCPKG_CXX=g++-9

install:
  - pushd $HOME
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - CC=$VCPKG_CC CXX=$VCPKG_CXX ./bootstrap-vcpkg.sh --disableMetrics
  - ./vcpkg integrate install
  - ./vcpkg install pcre pcre2 benchmark
  - popd

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build . -j 2
