name: Continuous Integration
on:
  push:
    branches:
      - master

jobs:
  osx-clang:
    name: macOS Clang
    runs-on: macos-latest
    env:
      CC: /usr/local/opt/llvm/bin/clang
      CXX: /usr/local/opt/llvm/bin/clang++
    steps:
      - uses: actions/checkout@v2
      - run: brew install ninja
      - run: env|sort
      - run: ls -l /usr/bin
      - run: ls -l /usr/local/bin
      - run: ls -l /usr/local
      - run: ls -l /usr/local/opt
      - run: ls -l /usr/local/Cellar
      - run: $CXX --version
      - name: Install Vcpkg
        run: |
          cd $HOME
          git clone --depth 1 https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh --disableMetrics
          ./vcpkg install $(< $GITHUB_WORKSPACE/.vcpkg)
      - name: Build Project
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build .
          ./example_simple

  osx-gcc:
    name: macOS GCC
    runs-on: macos-latest
    env:
      CC: gcc-9
      CXX: g++-9
    steps:
      - uses: actions/checkout@v2
      - run: brew install ninja
      - run: env|sort
      - run: ls -l /usr/bin
      - run: ls -l /usr/local/bin
      - name: Install Vcpkg
        run: |
          cd $HOME
          git clone --depth 1 https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh --disableMetrics
          ./vcpkg install $(< $GITHUB_WORKSPACE/.vcpkg)
      - name: Build Project
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build .
          ./example_simple

  linux-clang:
    name: Linux Clang
    runs-on: ubuntu-latest
    env:
      CC: clang-9
      CXX: clang++-9
    steps:
      - uses: actions/checkout@v2
      - run: env|sort
      - run: ls -l /usr/bin
      - run: ls -l /usr/local/bin
      - run: sudo apt-get install ninja-build
      - name: Install Vcpkg
        run: |
          cd $HOME
          git clone --depth 1 https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh --disableMetrics
          ./vcpkg install $(< $GITHUB_WORKSPACE/.vcpkg)
      - name: Build Project
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build .
          ./example_simple

  linux-gcc:
    name: Linux GCC
    runs-on: ubuntu-latest
    env:
      CC: gcc-9
      CXX: g++-9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install ninja-build
      - run: env|sort
      - run: ls -l /usr/bin
      - run: ls -l /usr/local/bin
      - name: Install Vcpkg
        run: |
          cd $HOME
          git clone --depth 1 https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh --disableMetrics
          ./vcpkg install $(< $GITHUB_WORKSPACE/.vcpkg)
      - name: Build Project
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build .
          ./example_simple

  windows-msvc:
    name: Windows MSVC
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: Get-ChildItem "Env:" | Sort Name
      - run: dir
      - run: dir "$GITHUB_WORKSPACE"
      - run: dir "$Env:ProgramFiles"
      - name: Install Vcpkg
        run: |
          cd $HOME
          New-Alias -Name git -Value "$Env:ProgramFiles\Git\bin\git.exe"
          git clone --quiet --depth 1 https://github.com/Microsoft/vcpkg.git vcpkg
          cd vcpkg
          .\bootstrap-vcpkg.bat -disableMetrics
          $packages = Get-Content "$Env:GITHUB_WORKSPACE\.vcpkg"
          .\vcpkg install --triplet x64-windows $packages
      - name: Build Project
        run: |
          New-Alias -Name cmake -Value "$Env:ProgramFiles\CMake\bin\cmake.exe"
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE="$HOME\vcpkg\scripts\buildsystems\vcpkg.cmake" ..
          cmake --build . --config Release
          .\Release\example_simple.exe
