name: Continuous Integration
on:
  push:
    branches:
      - master

jobs:
  linux-gcc:
    name: Linux GCC
    runs-on: ubuntu-latest
    env:
      CC: gcc-9
      CXX: g++-9
    steps:
      - name: Setup
        uses: actions/checkout@v2
      - run: env|sort
      - run: ls -l $HOME
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l /usr/bin
      - run: ls -l /usr/local/bin
      - run: clang++-9 --version
      - run: g++-9 --version
      - run: cmake --version

  osx-clang:
    name: macOS Clang
    runs-on: macos-latest
    env:
      CC: clang-9
      CXX: clang++-9
    steps:
      - name: Setup
        uses: actions/checkout@v2
      - run: env|sort
      - run: ls -l $HOME
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l /usr/bin
      - run: ls -l /usr/local/bin
      - run: clang++ --version
      - run: g++ --version
      - run: cmake --version

  windows-msvc:
    name: Windows MSVC
    runs-on: windows-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2
      - run: Get-ChildItem "Env:" | Sort Name
      - run: dir
      - run: dir "$GITHUB_WORKSPACE"
      - run: dir "$Env:HOMEPATH"
      - run: dir "$Env:ProgramFiles"
